// homelens-ui/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Dashboard from "./lib/dashboard/dashboard.svelte";
  import Header from "./lib/header.svelte";
  import AgentDetail from "./lib/agent/agentDetail.svelte";
  import { router } from "./router.svelte";
  import { agentStore } from "./ws.svelte";

  onMount(() => {
    agentStore.connect();
    return () => agentStore.disconnect();
  });

  const detailMatch = $derived(router.match("/agents/:id"));
</script>

<main class="relative w-full h-screen flex flex-col overflow-hidden">
  <Header />
  {#if detailMatch}
    <AgentDetail id={detailMatch.id} />
  {:else}
    <Dashboard />
  {/if}
</main>

// ui/src/App.tsx
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Header } from './components/header';
import { Dashboard } from './pages/dashboard/dashboard';
import AgentDetails from './pages/agentDetails/agentDetails';
import { useEffect } from 'react';
import { connectWS } from './services/websocket/agentSocket';

function App() {
  useEffect(() => {
    connectWS()
  }, [])

  return (
    <BrowserRouter>
      <main className="relative w-full h-screen flex flex-col overflow-hidden">
        <Header />
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/agents/:agentId" element={<AgentDetails />} />
        </Routes>
      </main>
    </BrowserRouter>
  );
}

export default App;
